### ISSUE TITLE
Cannot find  scoringutils::check_forecasts() 

### ISSUE THREAD

**Issue by RodrigoZepeda** [RodrigoZepeda/diseasenowcasting#58]
Line `218` of backtest.R. There doesn't seem to be that function inside `scoringutils`.

**Comment by RodrigoZepeda** [comment]
Error in `map2()`:
ℹ In index: 1.
Caused by error in `.f()`:
✖ Can't find `scoringutils::check_forecasts()`.

**Comment by ramiyaari** [comment]
I fixed the problem that were caused by a updates in a newer version of scoringutils

**Comment by ramiyaari** [comment]
I have with conflict in the pull request because you commented out the line there - not sure how to deal with conflicts
